#!/bin/sh

mypath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "${mypath/ttimdbcs*/}ttimdbcs/conf/ttsvc.conf"

cd ${ordsdir}
java -jar ${warfile} configdir ${ordsdir}
mkdir -p ${ordsdir}/${ordscontext}/jdbc/ccpmapi
cp ${ttsvc_config}/pool.xml ${ordsdir}/${ordscontext}/jdbc/ccpmapi
java -jar ${warfile} plugin ${ttsvc_pkgs}/classic-cp-mapi-0.0.1-SNAPSHOT.jar
java -jar ${warfile} plugin ${ttdir}/install/lib/ttjdbc8.jar
java -jar ${warfile} standalone --port ${ordsport} --context-path ${ordscontext} --apex-images ${ordscontext} --doc-root ${ordsdir} --static-context-path ${ordscontext} 2>&1 &
echo $! > ${ordsdir}/ords.pid
sleep 5 # let service find pidfile



